nginx:
  labels:
    io.rancher.container.pull_image: always
  image: nginx:1.13-3-alpine
  links:
  - 'cachet:'
  volumes:
  - cachetnginx:/etc/nginx/conf.d
  - cachetwww:/var/www
  volume_driver: convoy
cachet:
  environment:
    DB_DRIVER: pgsql
    DB_HOST: postgres
    DB_DATABASE: postgres
    DB_USERNAME: postgres
    DB_PASSWORD: ${POSTGRES_PASSWORD}
  labels:
    io.rancher.container.pull_image: always
  image: cachethq/docker:2.3.12
  links:
  - 'postgres:'
  volumes:
  - cachetwww:/var/www
  volume_driver: pxd
  labels:
        io.rancher.scheduler.affinity:host_label: pxfabric=px-cluster1
postgres:
  environment:
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  labels:
    io.rancher.container.pull_image: always
  image: postgres:9.4
  volumes:
  - cachetpgsql:/var/lib/postgresql/data
  volume_driver: pxd
  labels:
        io.rancher.scheduler.affinity:host_label: pxfabric=px-cluster1
